# Alacritty.

[general]
import = [
   "~/.config/alacritty/rose-pine.toml",
]

live_config_reload = false
ipc_socket = false

[window]
padding = { x = 3, y = 0 }
dynamic_padding = true
opacity = 0.9

[scrolling]
history = 0

[font]
normal = { family = "IosevkaTermSlab Nerd Font Mono", style = "Regular" }
size = 14

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 350
thickness = 0.35

[mouse]
hide_when_typing = true

[[keyboard.bindings]]
key = "F11"
action = "ToggleFullscreen"
